### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rhmaaa** [Accelergy-Project/pytorch2timeloop-converter#10]
site-packages/pytorch2timeloop-0.2-py3.7.egg/pytorch2timeloop/utils/interpreter.py", line 87, in run_node
    with self._set_current_node(n):
AttributeError: 'Converter' object has no attribute '_set_current_node'

**Comment by rhmaaa** [comment]
Could someone give me a soluton?

**Comment by gilbertmike** [comment]
Hi, thanks for reporting the error.

Unfortunately, I couldn't reproduce the bug. There is a recent merge, but I couldn't reproduce the bug before or after the merge commit. Could you try pulling the latest version and trying again?

If it still doesn't work, would you mind providing more details?

Some things that might be relevant:
- Your version of `torch`
- The network you're trying to convert

**Comment by rhmaaa** [comment]
> 

Thanks! I think that is question of my torch version. It can work when I change a conda environmen.
